version: '3.3'

services:
    jupyter:
        build: ./JupyterNotebook
        volumes:
            -   type: "bind"
                source: ./Datos/NotebooksJupyter
                target: /Datos
        ports:
            - 8888:8888
        command: bash -c "cd /Datos && jupyter notebook"
        depends_on:
            - postgres
        
    dash:
        build: ./Dash
        volumes:
            -   type: "bind"
                source: ./Datos/src_Dash
                target: /Datos
        ports: 
            - 8050:8050
        command: bash -c "python /Datos/app.py"
        depends_on:
            - postgres
    
    postgres:
        build: ./PostgreSQL
        volumes:
            -   type: "bind"
                source: ./Datos/scriptSQL
                target: /docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: covid